"""empty message

Revision ID: 015233e3e92e
Revises: 79b311ef4a0c
Create Date: 2023-01-06 00:42:50.570262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '015233e3e92e'
down_revision = '79b311ef4a0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('sexe',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('birthday',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('is_phone_visible',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_phone_visible',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('birthday',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('sexe',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
