"""Avis model modified

Revision ID: 072325430eb1
Revises: 5efa2c77d492
Create Date: 2023-01-09 14:06:22.458380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072325430eb1'
down_revision = '5efa2c77d492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver', sa.String(length=255), nullable=False))
        batch_op.drop_column('receiver_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('receiver',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('receiver',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('avis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('receiver')

    # ### end Alembic commands ###
