"""Message model edited

Revision ID: 1ae024a9121d
Revises: 072325430eb1
Create Date: 2023-01-10 23:14:50.668556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ae024a9121d'
down_revision = '072325430eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sended_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('edited_at')
        batch_op.drop_column('sended_at')

    # ### end Alembic commands ###
