"""adding format method to classes

Revision ID: 1f64447c23aa
Revises: 3122caa23467
Create Date: 2023-01-07 19:38:21.178740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f64447c23aa'
down_revision = '3122caa23467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trajets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_location', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('destination_location', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('start_hour', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('participation', sa.Float(), nullable=True))
        batch_op.drop_column('destination')
        batch_op.drop_column('price')
        batch_op.drop_column('hour')
        batch_op.drop_column('date')
        batch_op.drop_column('start')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trajets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('hour', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('destination', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('participation')
        batch_op.drop_column('start_hour')
        batch_op.drop_column('start_date')
        batch_op.drop_column('destination_location')
        batch_op.drop_column('start_location')

    # ### end Alembic commands ###
