"""Adding field to Ride Class

Revision ID: 5580d1d4afa8
Revises: 61ea555688f6
Create Date: 2023-03-02 11:09:13.246265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5580d1d4afa8'
down_revision = '61ea555688f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
