"""add modified_at to users

Revision ID: 58ce8e26d20b
Revises: 1f64447c23aa
Create Date: 2023-01-08 00:38:49.891289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ce8e26d20b'
down_revision = '1f64447c23aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('modified_at')

    # ### end Alembic commands ###
