"""Trajet model modified

Revision ID: 5efa2c77d492
Revises: c9a809ce00b4
Create Date: 2023-01-08 16:37:50.506732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5efa2c77d492'
down_revision = 'c9a809ce00b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trajets', schema=None) as batch_op:
        batch_op.alter_column('start_hour',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trajets', schema=None) as batch_op:
        batch_op.alter_column('start_hour',
               existing_type=sa.String(length=50),
               type_=postgresql.TIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
