"""Add fields to  User

Revision ID: 61ea555688f6
Revises: 056df74bef43
Create Date: 2023-02-28 21:26:55.211899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ea555688f6'
down_revision = '056df74bef43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_driver', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('registration_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('registration_date')
        batch_op.drop_column('is_email_verified')
        batch_op.drop_column('is_driver')

    # ### end Alembic commands ###
