"""Class def changed

Revision ID: 79b311ef4a0c
Revises: 
Create Date: 2023-01-04 23:52:57.866010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b311ef4a0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nbr_places_res', sa.Integer(), nullable=False))

    with op.batch_alter_table('trajets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nbr_places', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trajets', schema=None) as batch_op:
        batch_op.drop_column('nbr_places')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('nbr_places_res')

    # ### end Alembic commands ###
