"""Trajet model modified

Revision ID: c9a809ce00b4
Revises: 58ce8e26d20b
Create Date: 2023-01-08 15:56:42.250403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a809ce00b4'
down_revision = '58ce8e26d20b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=False))
        batch_op.drop_column('receiver')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('receiver_id')

    # ### end Alembic commands ###
