volumes:
  faaba-vol:

services:
  pgsql:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: faabadb
    volumes:
      - faaba-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432

  python:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - pgsql
    ports:
      - 80:5000
    volumes:
      - ./app:/usr/src/app